version: "3"

services:
  # Configure api service
  api:
    image: irfanghat/watchlistr_api
    environment:
      DATABASE_URL: "postgres://watchlistrdb_user:${POSTGRES_PASSWORD}@dpg-ck43mij6fquc73b0lipg-a.oregon-postgres.render.com/watchlistrdb"
    build:
    # Specify Dockerfile to used for
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  # Configure database service
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    
volumes:
  db:
    driver: local